app = 'tstun'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5000

  [[services.ports]]
    port = 5000

[[vm]]
  size = 'shared-cpu-1x'
